### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [SuneThomsenDK/Update-Office#1]
Hi,

Nice script. I have Office 2016 ProPlus en-us installation package that contains one extra language pack. You are stating that the updates needs to be installed in specific order if using language packs. Is there some official documentation somewhere regarding to this? 

I have been installing updates to Office using @seguraOSD's script (Install-OSDUpdatePackage.ps1) and I haven't had any issues installing updates to my multilang Office.

**Comment by SuneThomsenDK** [comment]
Hi,
Thx. No official documentation on that, but if you are installing Office 2016 during OSD with all updates included in the update folder in the root of Office 2016 installation share or if you do not use my arraylists which will install them in correct order, WSUS will re-apply some of the updates afterwards and add some extra time to your OSD.

We are installing Office 2016 ProPlus en-us as base installation, with two language packs and proofingkit on top of that, and I have to install updates in correct order for WSUS not to re-apply updates.
